### ISSUE TITLE
No support for episodic content (HL2 EP2)?

### ISSUE THREAD

**Issue by TheRealDannyyy** [Nbc66/source-sdk-2013-ce#1]
**First off, thanks a lot of for creating this fork!**

I'm fairly new to Source Modding and follow [this tutorial](https://jesseculver.com/tutorials/sp2013setup/) for the whole compilation process (minus the Microsoft Speech SDK stuff). I've reached the properties step and noticed that this fork doesn't have a separated project contexts, like the default solution has. 

Not sure if this is an issue or not but my end goal is to create a HL2 EP2 mod using this fork.
Is HL2 and Episodic merged into a single client/server project context or how does it work?

_Default Solution:_
![image](https://user-images.githubusercontent.com/15656049/92940407-61492a00-f44f-11ea-8803-8016afcd0a45.png)

_Forked Solution:_
![image](https://user-images.githubusercontent.com/15656049/92940340-4c6c9680-f44f-11ea-9fc3-719ec29147af.png)

**Comment by GamerDude27** [comment]
Hey, thanks for reaching out!

Sorry for the confusion, it should probably be stated somewhere, but SDK2013CE is "Episodic" by default.
I know there are a few differences between HL2 and EP2, but because I couldn't find a good enough reason to keep them both around I based it off of EP2. But I encourage anyone to reach out if there does exist a reason that's good enough to split it up again.

Hope this helps.

**Comment by TheRealDannyyy** [comment]
> Sorry for the confusion, it should probably be stated somewhere, but SDK2013CE is "Episodic" by default.
This is perfect for my personal needs but I guess for anyone that doesn't want it to be episodic, it would be worth mentioning in a wiki or similar documentation. A wiki or docs in general would be appreciated, especially for the new experimental features.

Thanks for the quick response!
