### ISSUE TITLE
Missing water texture in EP2 main menu

### ISSUE THREAD

**Issue by TheRealDannyyy** [Nbc66/source-sdk-2013-ce#3]
This could be caused by Valve's original map files. (Idea is to replace it with an example map instead.)

Example:
![water](https://user-images.githubusercontent.com/15656049/93006877-0d7b3580-f562-11ea-8436-955fdede081f.png)

Console:
![console](https://user-images.githubusercontent.com/15656049/93006882-1c61e800-f562-11ea-967a-9887e66a6004.png)

**Comment by AnthonyPython** [comment]
update we now know that it is caused by borked assets from the 2013 SP vpk's. which have broken maps, and some missing texture's. mounting like you normally would make it mount from the 2013 SP's content file versions instead of actual retail episodic content.

**Comment by breakdowngamesYT** [comment]
you closed my issue also i think its on your end it happends with multiple other computers i have and other versions of visual studio

**Comment by AnthonyPython** [comment]
> you closed my issue also i think its on your end it happends with multiple other computers i have and other versions of visual studio

Your issue was closed because none of it is reproducible and is in fact not on our end. It is clearly a problem with your own mod files and doesn't relate to the code base in any shape or form. as such it was closed. 

The only thing we can tell you is to verify that you have all nessary files that make up a source engine mod. 

The issue you described is missing or corrupted files for weapon text files and skill .cfg's, etc which  doesn't correlate with this code base in particular.

**Comment by breakdowngamesYT** [comment]
i literally copied all files from half life 2 stuffed em in my mod (yes the
vpks too) and am having the same issuse

**Comment by breakdowngamesYT** [comment]
if its not on your end could you provide me with a tutorial or something?
